spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/travelapp
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: super-secret-key-super-secret-key-super-secret-key
  expiration: 14400000
